using System.Collections;
using System.Collections.Generic;
using DG.Tweening;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using static Enum;

/// <summary>
/// (PUBLIC) ë³´ìƒ í‘œì‹œ íŒì—… (ê²Œì„ì¢…ë£Œ ë° ë³´ìƒìˆ˜ë ¹ì— ì‚¬ìš©)
/// </summary>
public class RewardUIManager : MonoBehaviour
{
    public GameObject rewardUIPopUp;            // ë³´ìƒ íŒì—…
    public TMP_Text newBestFloorMsgTxt;         // NEW ìµœê³ ì¸µ ë‹¬ì„± ë©”ì„¸ì§€ í…ìŠ¤íŠ¸
    public RewardSlotUI[] rewardSlotUIArr;      // ë³´ìƒ ìŠ¬ë¡¯UI ê°ì²´ë°°ì—´

    [Header("ëª¨ë“  ë³´ìƒí…œì„ ContentTfì•ˆì— ë¯¸ë¦¬ ë§Œë“¤ê³  IDXë¡œ ì²˜ë¦¬")]
    public Transform contentTf;

    int rwdCnt = 0;

    void Start()
    {
        InitDataAndUI();
    }

    void Update() {
        //! ë³´ìƒ í…ŒìŠ¤íŠ¸
        if(Input.GetKeyDown(KeyCode.V)) {
            // ë³´ìƒíšë“ (ê²°ê³¼íŒì—… í‘œì‹œ)
            if(rwdCnt % 2 == 0) // ì§ìˆ˜
            {
                ShowReward (
                    new Dictionary<RWD, int>
                    {
                        { RWD.ORE1, 50000 },
                        { RWD.ORE2, 50000 },
                        { RWD.ORE3, 50000 },
                        { RWD.ORE4, 50000 },
                        { RWD.CRISTAL, 10000 },
                        { RWD.ORE_CHEST, 10 },
                        { RWD.MAT1, 100 },
                        { RWD.MAT2, 100 },
                        { RWD.MAT3, 100 },
                        { RWD.MAT4, 100 },
                        { RWD.MAT5, 100 },
                        { RWD.MAT6, 100 },
                        { RWD.MAT7, 100 },
                        { RWD.MAT8, 100 },
                        { RWD.SKILLPOTION, 50 },
                        { RWD.TIMEPOTION, 50 },
                    }
                );
                rwdCnt++;
            }
            else // í™€ìˆ˜
            {
                ShowReward (
                    new Dictionary<RWD, int>
                    {
                        { RWD.ORE5, 50000 },
                        { RWD.ORE6, 50000 },
                        { RWD.ORE7, 50000 },
                        { RWD.ORE8, 50000 },
                        { RWD.CRISTAL, 50000 },
                        { RWD.TREASURE_CHEST, 100 },
                        { RWD.MUSH1, 200 },
                        { RWD.MUSH2, 200 },
                        { RWD.MUSH3, 200 },
                        { RWD.MUSH4, 200 },
                        { RWD.MUSH5, 200 },
                        { RWD.MUSH6, 200 },
                        { RWD.MUSH7, 200 },
                        { RWD.MUSH8, 200 },
                        { RWD.LIGHTSTONE, 10000 },
                    }
                );
                rwdCnt++;
            }
        }
    }

#region EVENT
    /// <summary>
    ///  ë³´ìƒ ìŠ¬ë¡¯UI íŒì—… ë‹«ê¸°
    /// </summary>
    public void OnClickDimScreenBtn() {
        // í™˜ìƒí•˜ê³ ë‚œë’¤ ë³´ìƒë‹«ê¸°ì‹œ ê²Œì„ ì¬ë¡œë“œ
        if(GM._.rbm.isRebornTrigger)
        {
            SceneManager.LoadScene("Game");
            return;
        }

        switch(GM._.gameState)
        {
            //* ì¸ê²Œì„ ì¢…ë£Œì˜ ê²½ìš°
            case GameState.TIMEOVER:
                GM._.gameState = GameState.HOME;
                rewardUIPopUp.SetActive(false);
                newBestFloorMsgTxt.gameObject.SetActive(false);

                GM._.pm.InitPlayData();

                // ì‹œë ¨ì˜ê´‘ì‚° ê²½ìš° ì¢…ë£Œì‹œ 
                if(GM._.stgm.IsChallengeMode)
                {
                    SoundManager._.PlayBgm(SoundManager.BGM.Home);
                    GM._.clm.ShowPopUp(); // ì‹œë ¨ì˜ê´‘ì‚° íŒì—… í‘œì‹œ
                    GM._.hm.Active();
                }
                // ì¼ë°˜ê´‘ì‚°ì˜ ê²½ìš° ì¢…ë£Œì‹œ
                else
                {
                    SoundManager._.PlayBgm(SoundManager.BGM.Home);
                    GM._.hm.Active();
                }
                break;
            //* ê·¸ ì´ì™¸
            default:
                rewardUIPopUp.SetActive(false);
                newBestFloorMsgTxt.gameObject.SetActive(false);
                break;
        }
    }
#endregion

#region FUNC
    /// <summary>
    /// ë³´ìƒ ê´€ë ¨ ë°ì´í„° ë° ê°ì²´ ì´ˆê¸°í™” (1íšŒ)
    /// </summary>
    private void InitDataAndUI() {
        // ë³´ìƒìŠ¬ë¡¯UIë¥¼ ë°°ì—´ë¡œ ì €ì¥ (ë¯¸ë¦¬ ContentTfì— ìŠ¬ë¡¯UI ì¶”ê°€í•˜ì—¬ ì¤€ë¹„)
        rewardSlotUIArr = new RewardSlotUI[contentTf.childCount];
        InitElement();
        ResetAllSlotUI();
    }

    /// <summary>
    /// ëª¨ë“  ì•„ì´í…œìŠ¬ë¡¯UI ê°ì²´ ì´ˆê¸°í™” (1íšŒ)
    /// </summary>
    private void InitElement() {
        for(int i = 0; i < contentTf.childCount; i++)
        {
            rewardSlotUIArr[i] = new RewardSlotUI
            {
                name = GetRewardItemName((RWD)i),
                rwdType = (RWD)i,
                DOTAnim = contentTf.GetChild(i).GetComponent<DOTweenAnimation>(),
                obj = contentTf.GetChild(i).gameObject,
                cntTxt = contentTf.GetChild(i).GetComponentInChildren<TMP_Text>(),
            };
        }
    }

    /// <summary>
    /// ë³´ìƒìŠ¬ë¡¯UI ë¦¬ì…‹ ì´ˆê¸°í™”
    /// </summary>
    private void ResetAllSlotUI() {
        for(int i = 0; i < contentTf.childCount; i++)
        {
            rewardSlotUIArr[i].cntTxt.text = "0";
            rewardSlotUIArr[i].obj.SetActive(false); // ë¹„í‘œì‹œ
        }
    }
    
    /// <summary>
    /// ë³´ìƒ ì•„ì´í…œ ì´ë¯¸ì§€ íšë“
    /// </summary>
    /// <param name="rwdType">ë³´ìƒíƒ€ì…</param>
    public Sprite GetRewardItemSprite(RWD rwdType)
    {
        const int ICON_ITEM = 1;

        Transform iconItemTf = rewardSlotUIArr[(int)rwdType].obj.transform.GetChild(ICON_ITEM);
        Image itemImg = iconItemTf.GetComponent<Image>();

        return itemImg.sprite;
    }

    /// <summary>
    ///* (ê²Œì„ì˜¤ë²„) íšë“í•œ ë³´ìƒ íŒì—… í‘œì‹œ 
    /// </summary>
    public void ShowGameoverReward(int[] gameoverRwdArr)
    {
        // ë³´ìƒìŠ¬ë¡¯ íŒì—… í‘œì‹œ
        GM._.rwm.rewardUIPopUp.SetActive(true);

        // ë³´ìƒìŠ¬ë¡¯UI ë¦¬ì…‹ ì´ˆê¸°í™”
        ResetAllSlotUI();

        // íšë“í•œ ë³´ìƒì•„ì´í…œ í‘œì‹œ
        int i = 0;
        foreach(int rwd in gameoverRwdArr)
        {
            // ë³´ìƒì¤‘ì— íšë“í•œê²Œ ìˆëŠ” ê²½ìš°
            if(rwd > 0)
            {
                // í•´ë‹¹ ë³´ìƒìŠ¬ë¡¯ í‘œì‹œ
                GM._.rwm.rewardSlotUIArr[i].obj.SetActive(true);
                GM._.rwm.rewardSlotUIArr[i].DOTAnim.DORestart();
                GM._.rwm.rewardSlotUIArr[i].cntTxt.text = rwd.ToString();
            }
            i++;
        }
    }

    /// <summary>
    /// ìˆ˜ë ¹í•  ë³´ìƒ íŒì—… í‘œì‹œ ë° ìˆ˜ì¹˜ ì¦ê°€
    /// </summary>
    /// <param name="rwdDic">ìˆ˜ë ¹í•  ë³´ìƒ Dicë¦¬ìŠ¤íŠ¸</param>
    public void ShowReward(Dictionary<RWD, int> rwdDic, bool isAutoMine = false) {
        // ë³´ìƒìŠ¬ë¡¯ íŒì—… í‘œì‹œ
        GM._.rwm.rewardUIPopUp.SetActive(true);

        // ë³´ìƒìŠ¬ë¡¯UI ë¦¬ì…‹ ì´ˆê¸°í™”
        GM._.rwm.ResetAllSlotUI();

        // íšë“í•  ë³´ìƒì•„ì´í…œ ì²˜ë¦¬
        foreach(var rwd in rwdDic)
        {
            if(rwd.Value > 0)
            {
                StatusDB sttDB = DM._.DB.statusDB;
                RWD rwdType = rwd.Key;     // íƒ€ì…
                int val = rwd.Value;            // íšë“ëŸ‰

                switch(rwdType)
                {   // (ê´‘ì„) ì¬í™”
                    case RWD.ORE1:
                    case RWD.ORE2:
                    case RWD.ORE3:
                    case RWD.ORE4:
                    case RWD.ORE5:
                    case RWD.ORE6:
                    case RWD.ORE7:
                    case RWD.ORE8:
                    case RWD.CRISTAL:
                        val = sttDB.SetRscArr((int)rwdType, val, isAutoMine);
                        break;
                    // (ì—°ê¸ˆìˆ ) ì¬ë£Œ
                    case RWD.MAT1:
                    case RWD.MAT2:
                    case RWD.MAT3:
                    case RWD.MAT4:
                    case RWD.MAT5:
                    case RWD.MAT6:
                    case RWD.MAT7:
                    case RWD.MAT8:
                        val = sttDB.SetMatArr((int)rwdType - (int)RWD.MAT1, val);
                        break;
                    // (ë²„ì„¯ë„ê°) ë²„ì„¯
                    case RWD.MUSH1:
                    case RWD.MUSH2:
                    case RWD.MUSH3:
                    case RWD.MUSH4:
                    case RWD.MUSH5:
                    case RWD.MUSH6:
                    case RWD.MUSH7:
                    case RWD.MUSH8:
                        val = sttDB.SetMsrArr((int)rwdType - (int)RWD.MUSH1, val);
                        break;

                    // (ì†Œë¹„) ì•„ì´í…œ
                    case RWD.ORE_TICKET: // ê´‘ì„ ì…ì¥í‹°ì¼“
                        sttDB.OreTicket += val;
                        break;
                    case RWD.RED_TICKET: // ì‹œë ¨ì˜ê´‘ì‚° ì…ì¥í‹°ì¼“
                        sttDB.RedTicket += val;
                        break;
                    case RWD.ORE_CHEST: // ê´‘ì„ìƒì
                        sttDB.OreChest += val;
                        break;
                    case RWD.TREASURE_CHEST: // ë³´ë¬¼ìƒì
                        sttDB.TreasureChest += val;
                        break;
                    case RWD.MUSH_BOX1: // ë²„ì„¯ìƒì1
                        sttDB.MushBox1 += val;
                        break;
                    case RWD.MUSH_BOX2: // ë²„ì„¯ìƒì2
                        sttDB.MushBox2 += val;
                        break;
                    case RWD.MUSH_BOX3: // ë²„ì„¯ìƒì3
                        sttDB.MushBox3 += val;
                        break;
                    case RWD.SKILLPOTION: // ìŠ¤í‚¬í¬ì…˜
                        sttDB.SkillPotion += val;
                        break;
                    case RWD.LIGHTSTONE: // ë¹›ë‚˜ëŠ”ëŒ
                        sttDB.LightStone += val;
                        break;
                    case RWD.TIMEPOTION: // ì‹œê°„ì˜í¬ì…˜
                        sttDB.TimePotion += val;
                        break;

                    // â€»ì—¬ê¸° ìœ„ì— ì¶”ê°€
                    case RWD.FAME: // ëª…ì˜ˆí¬ì¸íŠ¸ + (ì´ˆì›”) ëª…ì˜ˆ íšë“ëŸ‰
                        val += GM._.sttm.IncFame;
                        sttDB.Fame += val;
                        break;
                    
                }

                // í•´ë‹¹ ë³´ìƒìŠ¬ë¡¯UI í‘œì‹œ
                GM._.rwm.rewardSlotUIArr[(int)rwdType].obj.SetActive(true);
                GM._.rwm.rewardSlotUIArr[(int)rwdType].DOTAnim.DORestart();

                GM._.rwm.rewardSlotUIArr[(int)rwdType].cntTxt.text = val.ToString();
            }
        }

        // ì—…ê·¸ë ˆì´ë“œ ê°€ëŠ¥ì•Œë¦¼ğŸ”´ ìµœì‹ í™”
        GM._.ugm.UpdateAlertRedDotUI();
        GM._.mrm.UpdateAlertRedDotUI();
    }
#endregion
}
