using System.Collections;
using System.Collections.Generic;
using AssetKits.ParticleImage;
using DG.Tweening;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class TimePieceManager : MonoBehaviour
{
    public Coroutine CorActiveTimerID;
    const int TIMEPOTION_FILL_VAL = 500;
    int WAIT_TIME = 60; // 1ë¶„ë‹¹ íšŒë³µ

    public Sprite activeBtnSpr;
    public Sprite inActiveBtnSpr;

    public DOTweenAnimation DOTAnim;
    public DOTweenAnimation iconDOTAnim;
    public DOTweenAnimation iconrotateDOTAnim;
    public DOTweenAnimation rotateDOTAnim;

    //* ELEMENT
    public GameObject windowObj;
    public GameObject alertRedDotObj;
    public GameObject ingameActiveBtnObj;
    public Slider iconStorageSlider;
    public TMP_Text myLightStoneTxt;
    public TMP_Text timerTxt;
    public Image activeBtnImg;
    public TMP_Text gaugeValTxt;
    public Slider gaugeSlider;
    public TMP_Text timeScaleTxt;
    public TMP_Text decreaseValTxt;              // 1ì´ˆë‹¹ ì†Œëª¨ëŸ‰ í‘œì‹œí…ìŠ¤íŠ¸
    public TMP_Text timePotionCntTxt;            // ì‹œê°„ì˜í¬ì…˜ ìˆ˜ëŸ‰ í‘œì‹œí…ìŠ¤íŠ¸
    public ParticleImage timePotionChargeParticleEF; // ì‹œê°„ì˜í¬ì…˜ ì¶©ì „ ì´í™íŠ¸
    public Button autoActiveToggleBtn;           // ìë™ì‚¬ìš© í† ê¸€ë²„íŠ¼
    public TMP_Text autoActiveToggleBtnTxt;      // ìë™ì‚¬ìš© í† ê¸€ë²„íŠ¼ í…ìŠ¤íŠ¸

    [Header("ì—…ê·¸ë ˆì´ë“œ UI")]
    public UpgradeUIFormat upgFillValUI;         // 1ë¶„ë‹¹ íšŒë³µUI
    public UpgradeUIFormat upgIncStorageUI;      // ë³´ê´€ëŸ‰ ì¦ê°€UI
    public UpgradeUIFormat upgIncTimeScaleUI;    // ì‹œê°„ì†ë„ì¦ê°€UI

    //* VALUE
    // ìë™ì‹œì‘ íŠ¸ë¦¬ê±°
    public bool IsOnAutoActive {get => DM._.DB.timePieceDB.isAutoActiveTimePiece;}
    // ë°œë™ íŠ¸ë¦¬ê±°
    public bool isActive;
    // íšŒë³µ íƒ€ì´ë¨¸ì‹œê°„
    private int time;                            
    // ì‹œê°„ì˜ì¡°ê° ìµœëŒ€ë³´ê´€ëŸ‰
    public int MaxStorage {get => upgIncStorage.Val;}
    // ì‹œê°„ì˜ì¡°ê° í˜„ì¬ë³´ê´€ëŸ‰         
    public int curStorage;                       

    [Header("ì—…ê·¸ë ˆì´ë“œ ë°ì´í„°")]
    public UpgradeFormatInt upgFillVal;          // 1ë¶„ë‹¹ íšŒë³µ ë°ì´í„°
    public UpgradeFormatInt upgIncStorage;       // ë³´ê´€ëŸ‰ ì¦ê°€ ë°ì´í„°
    public UpgradeFormatFloat upgIncTimeScale;   // ì‹œê°„ì†ë„ì¦ê°€ ë°ì´í„°

    IEnumerator Start()
    {
        ingameActiveBtnObj.SetActive(false);

        // ë°ì´í„°ê°€ ë¨¼ì € ë¡œë“œë ë•Œê¹Œì§€ ëŒ€ê¸°
        yield return new WaitUntil(() => DM._.DB != null);
        // yield return new WaitUntil(() => DM._.DB.timePieceDB != null);
        
        // timePieceDBê°€ nullì¼ ê²½ìš° ìƒˆë¡œ ì´ˆê¸°í™”
        if (DM._.DB.timePieceDB == null)
        {
            Debug.Log("<color=red>ë°ì´í„°ê°€ ì—†ìŒìœ¼ë¡œ ìì²´ ì´ˆê¸°í™”</color>");
            DM._.DB.timePieceDB = new TimePieceDB();
            DM._.DB.timePieceDB.Init();
        }

        // í˜„ì¬ë³´ê´€ëŸ‰ ë°ì´í„°
        curStorage = DM._.DB.timePieceDB.curStorage;
        // 1ë¶„ë‹¹ íšŒë³µ ë°ì´í„°
        upgFillVal = DM._.DB.timePieceDB.upgFillVal;
        // ë³´ê´€ëŸ‰ ì¦ê°€ ë°ì´í„°
        upgIncStorage = DM._.DB.timePieceDB.upgIncStorage;
        // ì‹œê°„ì†ë„ì¦ê°€ ë°ì´í„°  
        upgIncTimeScale = DM._.DB.timePieceDB.upgIncTimeScale;

        //* ì˜¤í”„ë¼ì¸ ìë™íšë“ ê²°ê³¼ì²˜ë¦¬
        yield return new WaitForSeconds(1); // ì €ì¥ëœ ì¶”ê°€íšë“ëŸ‰ ë°ì´í„°ê°€ ë¡œë“œì•ˆë˜ëŠ” ë¬¸ì œê°€ ìˆì–´ 1ì´ˆ ëŒ€ê¸°

        OfflineAutoFill();
        SetSliderUI();
        UpdateToggleBtnUI(IsOnAutoActive);
    }

    // void Update() {
    //     //! TEST ìë™ì±„êµ´ ëŒ€ê¸°ì‹œê°„ 5ì´ˆ <-> 1ë¶„
    //     if(GM._.stm.testMode.activeSelf && Input.GetKeyDown(KeyCode.B))
    //     {
    //         if(WAIT_TIME == 60)
    //             WAIT_TIME = 5;
    //         else
    //             WAIT_TIME = 60;

    //         time = WAIT_TIME;
    //     }
    // }

#region EVENT
    /// <summary>
    /// ìë™ì‹œì‘ í† ê¸€ë²„íŠ¼
    /// </summary>
    public void OnToogleAutoActiveToggleBtn()
    {
        SoundManager._.PlaySfx(SoundManager.SFX.Tap1SFX);
        DM._.DB.timePieceDB.isAutoActiveTimePiece = !IsOnAutoActive;
        UpdateToggleBtnUI(IsOnAutoActive);
    }

    /// <summary>
    /// ë°œë™ë²„íŠ¼
    /// </summary>
    public void OnClickActiveBtn()
    {
        // ACTIVE -> STOP
        if(isActive)
        {
            isActive = false;
            ActiveProcess(isActive);
        }
        // STOP -> ACTIVE
        else
        {
            if(curStorage <= 0)
            {   // ì•„ì´í…œì´ ë¶€ì¡±í•©ë‹ˆë‹¤.
                GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NotEnoughItemMsg));
                return;
            }

            isActive = true;
            ActiveProcess(isActive);
        }
    }
    /// <summary>
    /// (ì—…ê·¸ë ˆì´ë“œ) 1ë¶„ë‹¹ íšŒë³µ ë²„íŠ¼
    /// </summary>
    public void OnClickUpgradeFillValBtn() => Upgrade(upgFillVal);
    /// <summary>
    /// (ì—…ê·¸ë ˆì´ë“œ) ë³´ê´€ëŸ‰ ì¦ê°€ ë²„íŠ¼
    /// </summary>
    public void OnClickUpgradeIncStorageBtn() => Upgrade(upgIncStorage);
    /// <summary>
    /// (ì—…ê·¸ë ˆì´ë“œ) ì‹œê°„ì†ë„ ì¦ê°€
    /// </summary>
    public void OnClickUpgradeIncTimeScaleBtn() => Upgrade(upgIncTimeScale);
    /// <summary>
    /// ì‹œê°„ì˜í¬ì…˜ ì‚¬ìš© ë²„íŠ¼
    /// </summary>
    public void OnClickUseTimePotion()
    {
        if(curStorage >= MaxStorage)
        {   // í˜„ì¬ ìµœëŒ€ì¹˜ì…ë‹ˆë‹¤.
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.MaxValMsg));
            return;
        }

        // ìˆ˜ëŸ‰ì²´í¬
        if(DM._.DB.statusDB.GetInventoryItemVal(Enum.INV.TIMEPOTION) <= 0) 
        {
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NotEnoughItemMsg));
            return;
        }

        SoundManager._.PlaySfx(SoundManager.SFX.ItemDrop1SFX);
        timePotionChargeParticleEF.Play();

        // ì‹œê°„ì˜í¬ì…˜ ìˆ˜ëŸ‰ê°ì†Œ
        DM._.DB.statusDB.SetInventoryItemVal(Enum.INV.TIMEPOTION, -1);
        // curStorage += TIMEPOTION_FILL_VAL;
        SetStorage(+TIMEPOTION_FILL_VAL);

        UpdateDataAndUI();
    }
#endregion

#region FUNC
    /// <summary>
    /// íŒì—…í‘œì‹œ
    /// </summary>
    public void ShowPopUp()
    {
        windowObj.SetActive(true);
        DOTAnim.DORestart();
        UpdateDataAndUI();
    }

    private void UpdateToggleBtnUI(bool isOn)
    {
        autoActiveToggleBtnTxt.text = isOn? "ON" : "OFF";
        autoActiveToggleBtnTxt.color = isOn? Color.green : Color.white;
    }

    /// <summary>
    /// ì‹œê°„ì˜ì¡°ê° í™œì„±í™” ë° ë¹„í™œì„±í™” ì²˜ë¦¬
    /// </summary>
    public void ActiveProcess(bool isActive)
    {
        if(!isActive)
        {
            SoundManager._.PlaySfx(SoundManager.SFX.Tap1SFX);
            activeBtnImg.sprite = inActiveBtnSpr;
            iconDOTAnim.DOPause();
            rotateDOTAnim.DOPause();
            iconrotateDOTAnim.DOPause();
            if(CorActiveTimerID != null)
                StopCoroutine(CorActiveTimerID);
            Time.timeScale = 1;
        }
        else
        {
            SoundManager._.PlaySfx(SoundManager.SFX.BlessResetSFX);
            activeBtnImg.sprite = activeBtnSpr;
            iconDOTAnim.DORestart();
            rotateDOTAnim.DORestart();
            iconrotateDOTAnim.DORestart();
            CorActiveTimerID = StartCoroutine(CoActiveTimer());
            Time.timeScale = upgIncTimeScale.Val;
        }

        timeScaleTxt.text = $"x {Time.timeScale}";
    }

    /// <summary>
    /// ì—…ê·¸ë ˆì´ë“œ ì²˜ë¦¬
    /// </summary>
    /// <param name="upgDt">ì—…ê·¸ë ˆì´ë“œí•  ë°ì´í„°</param>
    private void Upgrade(UpgradeFormat upgDt) {
        var sttDB = DM._.DB.statusDB;

        if(upgDt.IsMaxLv)
        {
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.MaxLvMsg));
            return;
        }

        if(sttDB.GetInventoryItemVal(upgDt.NeedRsc) >= upgDt.Price)
        {
            SoundManager._.PlaySfx(SoundManager.SFX.TranscendUpgradeSFX);
            GM._.ui.ShowNoticeMsgPopUp(LM._.Localize(LM.UpgradeCompleteMsg));

            // ì œì‘ì— í•„ìš”í•œ ì•„ì´í…œ ìˆ˜ëŸ‰ ê°ì†Œ
            sttDB.SetInventoryItemVal(upgDt.NeedRsc, -upgDt.Price);
            upgDt.Lv++;

            UpdateDataAndUI();

            // ì´ë¯¸ ì‹¤í–‰ì¤‘ì¸  ì‹œê°„ì˜ì¡°ê° í™œì„±í™”ê°€ ìˆë‹¤ë©´ ì •ì§€í•˜ì—¬ ì´ˆê¸°í™”
            if(CorActiveTimerID != null)
            {
                StopCoroutine(CorActiveTimerID);
                CorActiveTimerID = null;
            }

            ActiveProcess(isActive); // ì ìš©ë°ì´í„° ìµœì‹ í™”
        }
        else
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NotEnoughItemMsg));
    }

    /// <summary>
    /// ì—…ê·¸ë ˆì´ë“œ ê²°ê³¼ ìµœì‹ í™”
    /// </summary>
    private void UpdateDataAndUI()
    {
        upgFillVal.UpdatePrice(upgFillVal.PriceDef / 2);
        upgIncStorage.UpdatePrice(upgIncStorage.PriceDef / 2);
        upgIncTimeScale.UpdatePrice();

        upgFillValUI.UpdateUI(upgFillVal);
        upgIncStorageUI.UpdateUI(upgIncStorage);
        upgIncTimeScaleUI.UpdateUI(upgIncTimeScale);

        myLightStoneTxt.text = $"{DM._.DB.statusDB.LightStone}";
        timePotionCntTxt.text = $"{DM._.DB.statusDB.TimePotion}";
        decreaseValTxt.text = $"{LM._.Localize(LM.ConsumePerSec)} : {upgIncTimeScale.Val * 10}";

        // ìŠ¬ë¼ì´ë”UI ìµœì‹ í™”
        SetSliderUI();
    }

    /// <summary>
    /// ì˜¤í”„ë¼ì¸ ìë™íšŒë³µ ê²°ê³¼ì²˜ë¦¬
    /// </summary>
    private void OfflineAutoFill()
    {
        //* ì–´í”Œì‹œì‘ì‹œ ì´ì „ê¹Œì§€ ê²½ê³¼í•œì‹œê°„
        int passedTime = DM._.DB.autoMiningDB.GetPassedSecData();

        // ìë™íšë“ëŸ‰ ê³„ì‚°
        int cnt = passedTime / WAIT_TIME;

        // ê²°ê³¼
        int resVal = curStorage + cnt * GetProductionVal();

        // ìµœëŒ€ìˆ˜ëŸ‰ë³´ë‹¤ ë†’ë‹¤ë©´ ìµœëŒ€ìˆ˜ëŸ‰ë§Œí¼ìœ¼ë¡œ ìˆ˜ì •
        if(resVal > MaxStorage)
            resVal = MaxStorage;

        Debug.Log($"<color=white>ìë™íšë“ ì˜¤í”„ë¼ì¸ ì²˜ë¦¬: ì´ì „ìˆ˜ëŸ‰= {curStorage} / {MaxStorage}, íšë“ëŸ‰: {resVal} (ê²½ê³¼ì‹œê°„: {passedTime} / {WAIT_TIME} = {cnt})</color>");
        curStorage = resVal;

        time = WAIT_TIME;
    }

    /// <summary>
    /// ìë™íšŒë³µëŸ‰ ê³„ì‚° ë° ë°˜í™˜
    /// </summary>
    private int GetProductionVal() => upgFillVal.Val;

    /// <summary>
    /// ì‹œê°„ì˜ê²°ì • í˜„ì¬ë³´ê´€ëŸ‰ ì„¤ì •
    /// </summary>
    private void SetStorage(int val)
    {
        // ë³´ê´€ëŸ‰ ì¦ê°€ ë˜ëŠ” ê°ì†Œ
        curStorage += val;

        // ì‹œê°„ì˜ê²°ì •ì´ 0ì¸ê²½ìš° ì •ì§€
        if(curStorage <= 0)
        {
            curStorage = 0;
            isActive = false;
            ActiveProcess(isActive);
        }
    }

    private void SetSliderUI()
    {
        gaugeValTxt.text = $"{curStorage} / {MaxStorage}";
        
        // ë¶„ëª¨ê°€ 0ì¼ê²½ìš°, ë‚˜ëˆ„ê¸° ì—ëŸ¬ ë°œìƒí•˜ëŠ” ë¶€ë¶„ ëŒ€ì‘
        if (MaxStorage != 0)
        {
            gaugeSlider.value = (float)curStorage / MaxStorage;
            iconStorageSlider.value = (float)curStorage / MaxStorage;
        }
        else
        {
            gaugeSlider.value = 0;
            iconStorageSlider.value = 0;
        }

        // ğŸ”´ì•ŒëŒ (ì¡°ê±´1: ì‹œê°„ì˜ì¡°ê° ìµœëŒ€ì¹˜ì´ìƒ ë³´ìœ ì‹œ + ì¡°ê±´2:ì‹œê°„ì˜ì¡°ê°ì´ ë¯¸ì‚¬ìš©ì¤‘ì¼ë•Œ)
        alertRedDotObj.SetActive(curStorage >= MaxStorage && !isActive);
    }

    public IEnumerator CoActiveTimer()
    {
        // ì†Œìˆ˜ì  ë‚˜ë¨¸ì§€
        float remain = 0;

        while(isActive)
        {
            if(!isActive)
                break;

            yield return Util.TIME0_1;

            // ì‹œê°„ì†ë„ ì—…ê¸€ì‹œ, ê·¸ ìˆ˜ì¹˜ë§Œí¼ %ë¡œ ë” ê°ì†ì´ ë¹¨ë¦¬ë˜ë„ë¡ ë‚˜ë¨¸ì§€ê°’ ì ìš©
            float remainVal = (int)upgIncTimeScale.Val - upgIncTimeScale.Val;
            remain += remainVal;
            // ì†Œìˆ˜ì  ë‚˜ë¨¸ì§€ê°’ì´ í•©ì‚°ë˜ì–´ 1ë³´ë‹¤ë†’ë‹¤ë©´ ì¶”ê°€ì ìœ¼ë¡œ ê²Œì´ì§€ ê°ì†Œ
            if(remain >= 1)
            {
                SetStorage(-(int)upgIncTimeScale.Val - 1);
                remain -= 1;
            }
            else
            {
                SetStorage(-(int)upgIncTimeScale.Val); // ê²Œì´ì§€ ê°ì†Œ
            }

            SetSliderUI();
        }
    }

    /// <summary>
    /// íƒ€ì´ë¨¸ (1ë¶„)
    /// </summary>
    public void SetTimer()
    {
        // ìµœëŒ€ìˆ˜ëŸ‰ ë„˜ì–´ê°ˆì‹œ ì²˜ë¦¬ì•ˆí•¨
        if(curStorage >= MaxStorage)
        {
            if(timerTxt.text != "00 : 00")
                timerTxt.text = "00 : 00";
            return;
        }
        
        time--;
        string timeFormat = Util.ConvertTimeFormat(time);
        timerTxt.text = timeFormat;

        // ë¦¬ì…‹
        if(time < 1)
        {
            time = WAIT_TIME;
            SetStorage(GetProductionVal());
            SetSliderUI();
        }
    }
#endregion
}