using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UIElements;
using static Enum;

public class AutoMiningManager : MonoBehaviour
{
    int WAIT_TIME = 60; // ì±„êµ´ íšë“ ëŒ€ê¸°ì‹œê°„
    const int ORE_INC_UNIT = 100; // ìë™ì±„êµ´ ìµœëŒ€ë³´ê´€ëŸ‰ ì¦ê°€ ë‹¨ìœ„

    [Header("ìë™ì±„êµ´ ìˆ˜ë ¹ë²„íŠ¼ ì•ŒëŒì•„ì´ì½˜ í‘œì‹œ")]
    public GameObject[] autoMiningBtnAlertRedDotArr;

    [Header("ìë™ì±„êµ´ íŒì—…")]
    public GameObject windowObj;
    public GameObject alertRedDotObj;
    public GameObject acceptAllAlertRedDotObj;
    public TMP_Text timerTxt;
    public AutoMiningFormat[] autoMiningArr;
    
    private int time;

    [Header("ì‹œë ¨ì˜ê´‘ì‚° ìë™ì±„êµ´")]
    public GameObject cristalAlertRedDotObj;
    public TMP_Text cristalTimerTxt;
    private int cristalTime;

    StatusDB sttDB;
    StageDB stgDB;
    AutoMiningDB autoDB;

    IEnumerator Start() {
        // ë°ì´í„°ê°€ ë¨¼ì € ë¡œë“œë ë•Œê¹Œì§€ ëŒ€ê¸°
        yield return new WaitUntil(() => DM._.DB != null);

        sttDB = DM._.DB.statusDB;
        stgDB = DM._.DB.stageDB;
        autoDB = DM._.DB.autoMiningDB;

        //* ì˜¤í”„ë¼ì¸ ìë™ì±„êµ´ ê²°ê³¼ì²˜ë¦¬
        yield return new WaitForSeconds(1); // ì €ì¥ëœ ì¶”ê°€íšë“ëŸ‰ ë°ì´í„°ê°€ ë¡œë“œì•ˆë˜ëŠ” ë¬¸ì œê°€ ìˆì–´ 1ì´ˆ ëŒ€ê¸°

        OfflineAutoMining();
        UpdateAll();
        // StartCoroutine(CoTimerStart());
    }

    void Update() {
        //! TEST ìë™ì±„êµ´ ëŒ€ê¸°ì‹œê°„ 5ì´ˆ <-> 1ë¶„
        if(Input.GetKeyDown(KeyCode.B))
        {
            if(WAIT_TIME == 60)
                WAIT_TIME = 5;
            else
                WAIT_TIME = 60;
            
            GM._.ui.ShowNoticeMsgPopUp($"(í…ŒìŠ¤íŠ¸ëª¨ë“œ) ìë™ì±„êµ´ ë° ì‹œê°„ì¡°ê° ìë™íšë“ ëŒ€ê¸°ì‹œê°„ <color=red>{WAIT_TIME}</color>ì´ˆë¡œ ë³€ê²½");

            time = WAIT_TIME;
            cristalTime = WAIT_TIME;
        }
    }

#region EVENT
    /// <summary>
    /// ì¼ê´„ìˆ˜ë ¹ ë²„íŠ¼
    /// </summary>
    public void OnClickAcceptAllBtn()
    {
        // ëª¨ì¸ê´‘ì„ì´ í•˜ë‚˜ë„ ì—†ì„ê²½ìš°
        if(Array.TrueForAll(autoMiningArr, mine => mine.CurStorage <= 0))
        {   // ëª¨ì¸ê´‘ì„ì´ ì—†ìŠµë‹ˆë‹¤ ë©”ì„¸ì§€ í‘œì‹œ
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NoOreYetMsg));
            return;
        }

        SoundManager._.PlaySfx(SoundManager.SFX.AutoMiningTakeSFX);

        //* ë³´ìƒ íšë“
        GM._.rwm.ShowReward (
            new Dictionary<RWD, int> { 
                {RWD.ORE1, autoMiningArr[0].CurStorage},
                {RWD.ORE2, autoMiningArr[1].CurStorage},
                {RWD.ORE3, autoMiningArr[2].CurStorage},
                {RWD.ORE4, autoMiningArr[3].CurStorage},
                {RWD.ORE5, autoMiningArr[4].CurStorage},
                {RWD.ORE6, autoMiningArr[5].CurStorage},
                {RWD.ORE7, autoMiningArr[6].CurStorage},
                {RWD.ORE8, autoMiningArr[7].CurStorage},
            },
            isAutoMine: true
        );

        // ë³´ê´€ëŸ‰ 0ìœ¼ë¡œ ì´ˆê¸°í™”
        for(int i = 0; i < autoMiningArr.Length; i++)
        {
            autoMiningArr[i].CurStorage = 0;
        }

        // ì—…ë°ì´íŠ¸ UI
        UpdateUI();
    }
    /// <summary>
    /// ìë™ì±„êµ´ ê´‘ì„ ìˆ˜ë ¹ ë²„íŠ¼ 
    /// </summary>
    /// <param name="idx">ê´‘ì„:(0 ~ 7), í¬ë¦¬ìŠ¤íƒˆ : 8</param>
    public void OnClickTakeStorageBtn(int idx)
    {
        AutoMiningFormat am = autoMiningArr[idx];

        if(am.CurStorage <= 0)
        {
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NoOreYetMsg));
            return;
        }

        SoundManager._.PlaySfx(SoundManager.SFX.AutoMiningTakeSFX);
        GM._.ui.ShowNoticeMsgPopUp(LM._.Localize(LM.ReceiptCompletedMsg));

        //* ë³´ìƒ íšë“
        GM._.rwm.ShowReward (
            new Dictionary<RWD, int> { {(RWD)idx, am.CurStorage} },
            isAutoMine: true
        );
        
        // ë³´ê´€ëŸ‰ ì´ˆê¸°í™”
        am.CurStorage = 0;

        // ì—…ë°ì´íŠ¸ UI
        UpdateUI();
    }

    /// <summary>
    /// ìµœëŒ€ë³´ê´€ëŸ‰ ì—…ê·¸ë ˆì´ë“œ ë²„íŠ¼
    /// </summary>
    public void OnClickUpgradeBtn(int idx)
    {
        AutoMiningFormat am = autoMiningArr[idx];

        if(am.Type == RSC.CRISTAL)
        {
            // í¬ë¦¬ìŠ¤íƒˆ ê´‘ì„ ì—…ê·¸ë ˆì´ë“œì— í•„ìš”í•œ ê´‘ì„ ë¡œí…Œì´ì…˜ 
            idx = GetCristalUpgradeOreIdx(am.Lv);

            if(sttDB.RscArr[idx] < am.upgradePrice)
            {
                GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NotEnoughItemMsg));
                return;
            }
        }
        else
        {
            if(sttDB.RscArr[idx] < am.upgradePrice)
            {
                GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.NotEnoughItemMsg));
                return;
            }
        }

        SoundManager._.PlaySfx(SoundManager.SFX.UpgradeSFX);

        GM._.ui.ShowNoticeMsgPopUp(LM._.Localize(LM.UpgradeMaxStorage) + "!");

        // ì¬í™” ê°ì†Œ
        sttDB.SetRscArr(idx, -am.upgradePrice);

        // ë ˆë²¨ ì—…
        am.Lv++;

        // ì—…ë°ì´íŠ¸
        UpdateAll();
    }
#endregion

#region FUNC
    /// <summary>
    /// ì˜¤í”„ë¼ì¸ ìë™ì±„êµ´ ê²°ê³¼ì²˜ë¦¬
    /// </summary>
    private void OfflineAutoMining()
    {
        Debug.Log("OfflineAutoMining():: ìë™ì±„êµ´ ì˜¤í”„ë¼ì¸ ì²˜ë¦¬");

        AutoMiningSaveData[] svDts = DM._.DB.autoMiningDB.saveDts;

        //* ì–´í”Œì‹œì‘ì‹œ ì´ì „ê¹Œì§€ ê²½ê³¼í•œì‹œê°„
        int passedTime = DM._.DB.autoMiningDB.GetPassedSecData();

        // ë°ì´í„°ë¡œë“œ : AutoMiningFormatí´ë˜ìŠ¤ê°€ UIë³€ìˆ˜ë„ ìˆì–´ì„œ ê°ì²´ìƒì„±ì€ ì•ˆë˜ê³ , ì €ì¥ëœ ë°ì´í„°ë§Œ ëŒ€ì…
        for(int i = 0; i < autoMiningArr.Length; i++)
        {
            // ì ê¸ˆí•´ì œê°€ ì•ˆë¬ë‹¤ë©´ ì´í•˜ì²˜ë¦¬ ì•ˆí•¨
            if(!svDts[i].IsUnlock)
                continue;

            // Debug.Log($"ìë™ì±„êµ´ ê´‘ì„{i+1} : ì´ì „ëŸ‰= {autoMiningArr[i].CurStorage}");

            // ë°ì´í„° ë¡œë“œ ìµœì‹ í™”
            RSC oreType = autoMiningArr[i].Type;
            {
                // ì ê¸ˆí•´ì œ ìƒíƒœ
                autoMiningArr[i].IsUnlock = svDts[i].IsUnlock;
                // ë ˆë²¨
                autoMiningArr[i].Lv = svDts[i].Lv;
                // ê²½ê³¼ì‹œê°„
                autoMiningArr[i].Time = svDts[i].Time;  
                // í˜„ì¬ë³´ê´€ëŸ‰
                autoMiningArr[i].CurStorage = svDts[i].CurStorage; 
                // ìµœëŒ€ë³´ê´€ëŸ‰
                if(i == (int)RSC.CRISTAL)
                    autoMiningArr[i].maxStorage = CalcMaxCristalStorage(autoMiningArr[i].Lv);
                else
                    autoMiningArr[i].maxStorage = CalcMaxOreStorage(autoMiningArr[i].Lv);
            }

            // ìë™ì±„êµ´ íšë“ëŸ‰ ê³„ì‚°
            int cnt = passedTime / WAIT_TIME; //(type == RSC.CRISTAL? HOUR : MINUTE);

            // ìë™ì±„êµ´ ê²°ê³¼ìˆ˜ëŸ‰ //! ì´ë¯¸ ìˆ˜ë ¹í• ë•Œ ëª¨ë‘ ì ìš©ëœìƒíƒœë¡œ ì–»ê¸°ë•Œë¬¸ì— í˜„ì¬ ì•„ë˜ì˜ GetProductionValê°€ ìˆìœ¼ë©´ ì¤‘ë³µì´ ë˜ëŠ” ìƒíƒœì„.
            int resVal = autoMiningArr[i].CurStorage + cnt * GetProductionVal((RSC)i);

            // ìµœëŒ€ìˆ˜ëŸ‰ë³´ë‹¤ ë†’ë‹¤ë©´ ìµœëŒ€ìˆ˜ëŸ‰ë§Œí¼ìœ¼ë¡œ ìˆ˜ì •
            if(resVal > autoMiningArr[i].maxStorage)
                resVal = autoMiningArr[i].maxStorage;

            Debug.Log($"<color=white>ìë™ì±„êµ´ ì˜¤í”„ë¼ì¸ ì²˜ë¦¬ {oreType}: ì´ì „ìˆ˜ëŸ‰= {autoMiningArr[i].CurStorage} / {autoMiningArr[i].maxStorage}, íšë“ëŸ‰: {resVal} (ê²½ê³¼ì‹œê°„: {passedTime} / {WAIT_TIME} = {cnt})</color>");
            autoMiningArr[i].CurStorage = resVal;
        }

        time = WAIT_TIME;
        cristalTime = WAIT_TIME;
    }

    /// <summary>
    /// ê´‘ì„ ë° í¬ë¦¬ìŠ¤íƒˆ 1ë¶„ë‹¹ ìë™ì±„êµ´ëŸ‰ ê³„ì‚° ë° ë°˜í™˜
    /// </summary>
    /// <param name="rscType"></param>
    /// <returns></returns>
    private int GetProductionVal(RSC rscType)
    {
        if(rscType == RSC.CRISTAL)
        {
            int extraVal = stgDB.BestFloorArr[(int)RSC.CRISTAL] + GM._.sttm.ExtraIncCristal;
            float extraPer = 1 + GM._.sttm.ExtraAutoCristalPer;
            Debug.Log($"ìë™ì±„êµ´ ìƒì‚°ëŸ‰: GetProductionVal({rscType}):: extraVal({extraVal}) * extraPer({extraPer})");
            return Mathf.RoundToInt(extraVal * extraPer);
        }
        else
        {
            int extraVal = stgDB.BestFloorArr[(int)rscType] * ORE_INC_UNIT;
            float extraPer = 1 + GM._.sttm.ExtraAutoOrePer;
            Debug.Log($"ìë™ì±„êµ´ ìƒì‚°ëŸ‰: GetProductionVal({rscType}):: extraVal({extraVal}) * extraPer({extraPer})");
            return Mathf.RoundToInt(extraVal * extraPer);
        }
    }

    /// <summary>
    /// ìë™ì±„êµ´ ê´‘ì„ ì¦ê°€ (ê´‘ì„íƒ€ì…)
    /// </summary>
    private void SetStorage(int idx)
    {
        AutoMiningFormat am = autoMiningArr[idx];

        // ì ê¸ˆí•´ì œëœ ê´‘ì„ë§Œ
        if(am.IsUnlock)
        {
            // ê´‘ì„ ë° í¬ë¦¬ìŠ¤íƒˆ ìë™ì±„êµ´ëŸ‰
            int val = GetProductionVal((RSC)idx);

            // ìˆ˜ëŸ‰ ì¦ê°€
            am.CurStorage += val; 

            // ìµœëŒ€ìˆ˜ëŸ‰ ë‹¤ ì±„ì› ì„ ê²½ìš°
            if(am.CurStorage >= am.maxStorage)
            {
                am.curStorageTxt.color = Color.red;
                am.CurStorage = am.maxStorage;
            }
        }
    }

    /// <summary>
    /// ê´‘ì„ ìë™ì±„êµ´ (1ë¶„)
    /// </summary>
    public void SetOreTimer()
    {
        time--;
        string timeFormat = Util.ConvertTimeFormat(time);
        timerTxt.text = timeFormat;

        // ë¦¬ì…‹
        if(time < 1)
        {
            time = WAIT_TIME;

            // ìë™ì±„êµ´ ì²˜ë¦¬
            int oreLenght = autoMiningArr.Length - 1; // í¬ë¦¬ìŠ¤íƒˆì€ ì œì™¸
            for(int i = 0; i < oreLenght; i++)
            {
                SetStorage(i);
            }

            UpdateUI();
        }
    }
    /// <summary>
    /// í¬ë¦¬ìŠ¤íƒˆ ìë™ì±„êµ´ (1ë¶„)
    /// </summary>
    public void SetCristalTimer()
    {
        cristalTime--;
        string timeFormat = Util.ConvertTimeFormat(cristalTime);
        cristalTimerTxt.text = timeFormat;

        // ë¦¬ì…‹
        if(cristalTime < 1)
        {
            Debug.Log($"SetCristalTimer():: cristalTime= {cristalTime}");
            cristalTime = WAIT_TIME;

            // í¬ë¦¬ìŠ¤íƒˆ ìë™ì±„êµ´ ì²˜ë¦¬
            SetStorage((int)RSC.CRISTAL);

            UpdateUI();
        }
    }

    public void UpdateAll()
    {
        UpdateData();
        UpdateUI();
    }

    private void UpdateData()
    {
        // ê°•í™”ë¹„ìš© ê°ì†Œ%
        float decreasePer = 1 - GM._.rbm.upgDecUpgradePricePer.Val;

        for(int i = 0; i < autoDB.saveDts.Length; i++)
        {
            AutoMiningFormat am = autoMiningArr[i];

            // ìµœëŒ€ë³´ê´€ëŸ‰
            if(i == (int)RSC.CRISTAL)
                am.maxStorage = CalcMaxCristalStorage(am.Lv);
            else
                am.maxStorage = CalcMaxOreStorage(am.Lv);

            // ì±„êµ´ëŸ‰
            am.productionVal = stgDB.BestFloorArr[i];

            // ê°€ê²©
            if(i == (int)RSC.CRISTAL)
            {
                am.upgradePrice = Mathf.RoundToInt(CalcUpgradCristalPrice(am.Lv) * decreasePer);
            }
            else
            {
                am.upgradePrice = Mathf.RoundToInt(CalcUpgradeOrePrice(am.Lv) * decreasePer);
            }
        }
    }

    private void UpdateUI()
    {
        alertRedDotObj.SetActive(false);
        acceptAllAlertRedDotObj.SetActive(false);
        cristalAlertRedDotObj.SetActive(false);

        for(int i = 0; i < autoDB.saveDts.Length; i++)
        {
            AutoMiningSaveData saveDt = autoDB.saveDts[i];
            AutoMiningFormat am = autoMiningArr[i];

            // ì ê¸ˆí•´ì œ í™”ë©´ (setter: UI ì—…ë°ì´íŠ¸)
            am.IsUnlock = saveDt.IsUnlock;

            // íƒ€ì´í‹€
            if(i != (int)RSC.CRISTAL)
                am.titleTxt.text = $"{LM._.Localize($"UI_MineStage{i + 1}")} {stgDB.BestFloorArr[i]}{LM._.Localize(LM.Floor)}";

            // í˜„ì¬ìˆ˜ëŸ‰ì´ ìµœëŒ€ìˆ˜ëŸ‰ë§Œí¼ ìŒ“ì˜€ëŠ”ì§€ì— ë”°ë¥¸ ìƒ‰ê¹”íƒœê·¸
            string isFullcolorTag = am.CurStorage >= am.maxStorage? "red" : "white";

            // í˜„ì¬ìˆ˜ëŸ‰
            am.curStorageTxt.text = $"<color={isFullcolorTag}><sprite name={am.Type}> {am.CurStorage} / {am.maxStorage}</color>";
            autoMiningBtnAlertRedDotArr[i].SetActive(am.CurStorage >= am.maxStorage);

            // ì±„êµ´ëŸ‰
            am.productionValTxt.text = $"{LM._.Localize(LM.MiningPerMin)} +{GetProductionVal((RSC)i)}";

            if(i == (int)RSC.CRISTAL)
            {
                // ê°€ê²©
                int rotateOreIdx = GetCristalUpgradeOreIdx(am.Lv);
                am.UpgradePriceBtnTxt.text = $"<size=65%><sprite name=ORE{rotateOreIdx + 1}></size>{am.upgradePrice}";
            }
            else
            {
                // ê°€ê²©
                am.UpgradePriceBtnTxt.text = $"{am.upgradePrice}";
            }

            // ë‹¤ìŒ ì—…ê·¸ë ˆì´ë“œ ìµœëŒ€ë³´ê´€ëŸ‰ í‘œì‹œ
            if(i == (int)RSC.CRISTAL)
                am.UpgradeInfoTxt.text = $"{am.maxStorage} => {CalcMaxCristalStorage(am.Lv + 1)}";
            else
                am.UpgradeInfoTxt.text = $"{am.maxStorage} => {CalcMaxOreStorage(am.Lv + 1)}";

            // ì—…ë°ì´íŠ¸ ì•Œë¦¼UI ğŸ”´
            UpdateAlertRedDotUI(i);
        }

        acceptAllAlertRedDotObj.SetActive(alertRedDotObj.activeSelf);
    }

    private void UpdateAlertRedDotUI(int idx)
    {
        AutoMiningFormat am = autoMiningArr[idx];

            if(idx == (int)RSC.CRISTAL)
            {
                if(am.CurStorage >= am.maxStorage && !cristalAlertRedDotObj.activeSelf)
                    cristalAlertRedDotObj.SetActive(true);
            }
            else
            {
                if(am.CurStorage >= am.maxStorage && !alertRedDotObj.activeSelf)
                    alertRedDotObj.SetActive(true);
            }
    }

    private int GetCristalUpgradeOreIdx(int lv)
    {
        return (lv - 1) % ((int)RSC.ORE8 + 1);
    }

    private int CalcMaxOreStorage(int lv)
    {
        const int DEF = 100, INC = 100;

        // ì¶”ê°€ ìˆ˜ëŸ‰
        float extraPer = 1 + GM._.sttm.ExtraAutoOreBagStoragePer; // (ì´ˆì›”) ìë™ ê´‘ì„ ë³´ê´€ëŸ‰%

        int val = DEF + (lv - 1) * INC;

        return Mathf.RoundToInt(val * extraPer * GM._.fm.CalcAllAutoMiningStorageMultiVal(GM._.fm.FameLv));
    }

    private int CalcMaxCristalStorage(int lv)
    {
        const int DEF = 10, INC = 10;

        // ì¶”ê°€ ìˆ˜ëŸ‰
        float extraPer = 1 + GM._.sttm.ExtraAutoCristalBagStoragePer; // (ì´ˆì›”) ìë™ í¬ë¦¬ìŠ¤íƒˆ ë³´ê´€ëŸ‰%

        int val = DEF + (lv - 1) * INC;

        return Mathf.RoundToInt(val * extraPer * GM._.fm.CalcAllAutoMiningStorageMultiVal(GM._.fm.FameLv));
    }

    /// <summary>
    /// ìë™ì±„êµ´ ì¼ë°˜ê´‘ì„ ìµœëŒ€ë³´ê´€ëŸ‰ ì—…ê·¸ë ˆì´ë“œ ê°€ê²©
    /// </summary>
    private int CalcUpgradeOrePrice(int lv)
    {
        return 500 + (lv - 1) * 500;
    }

    /// <summary>
    /// ìë™ì±„êµ´ ì¼ë°˜ê´‘ì„ ìµœëŒ€ë³´ê´€ëŸ‰ ì—…ê·¸ë ˆì´ë“œ ê°€ê²©
    /// </summary>
    private int CalcUpgradCristalPrice(int lv)
    {
        return 1000 + ( lv * ( lv - 1 ) * 1000 ) / 2;
    }
#endregion
}
