using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using static Enum;

public class FameManager : MonoBehaviour
{
    const int FAME_MAXLV = 30;

    [Header("ë²„íŠ¼ ìˆ˜ë ¹ê°€ëŠ¥í•œì§€ì— ë”°ë¥¸ ìƒ‰ê¹” ìŠ¤í”„ë¼ì´íŠ¸")]
    public Sprite grayBtnSpr;
    public Sprite yellowBtnSpr;

    [Space(15)]

    public GameObject windowObj;
    public GameObject alertRedDotObj;
    public Slider fameExpSlider;
    public TMP_Text fameLvTxt;
    public TMP_Text fameExpTxt;

    [Header("ëª…ì˜ˆ ë ˆë²¨ì—… ì •ë³´ íŒ¨ë„ : ìºë¦­í„° ê³ ìš© ëœë¤í…Œì´ë¸” í™•ì¸ìš©ìœ¼ë¡œë„ ì‚¬ìš©")]
    public GameObject fameLevelUpInfoPanel;
    public TMP_Text fameLevelUpInfoPanelTitleTxt;
    public TMP_Text fameLevelUpInfoPanelLvTxt;
    public TMP_Text employRandomTableValTxt;
    public TMP_Text allAutoMiningStorageMultiplyValTxt; // ëª…ì˜ˆ ë ˆë²¨ì—ë”°ë¥¸ ëª¨ë“  ìë™ì±„êµ´ë³´ê´€ëŸ‰ ê³±í•˜ê¸°ê°’ í…ìŠ¤íŠ¸

    public Toggle nextLvInfoToogleHandle;

    public int FameLv {
        get => DM._.DB.statusDB.FameLv;
        set => DM._.DB.statusDB.FameLv = value;
    }
    public int FameExp { 
        get => DM._.DB.statusDB.Fame;
        set => DM._.DB.statusDB.Fame = value;
    }
    public int fameMaxExp {
        get => CalcFameMaxExp(FameLv);
    }

    [field:Header("ë¯¸ì…˜: ê´‘ì„ì±„êµ´, ì±„êµ´ì‹œê°„, ê°•í™”í•˜ê¸°, ê´‘ì‚° í´ë¦¬ì–´, ë³´ë¬¼ìƒì ì±„êµ´, ì‹œë ¨ì˜ê´‘ì‚° ëŒíŒŒ")]

    [Header("ë¯¸ì…˜ ë°ì´í„° : Start()í•¨ìˆ˜ì—ì„œ ì´ˆê¸°í™”")]
    public MissionFormat[] missionArr;

    [Header("ë¯¸ì…˜ UI")]
    public MissionUIFormat[] missionUIArr;

    IEnumerator Start()
    {
        // ë°ì´í„°ê°€ ë¨¼ì € ë¡œë“œë ë•Œê¹Œì§€ ëŒ€ê¸°
        yield return new WaitUntil(() => DM._.DB != null);

        var svDts = DM._.DB.missionDB.saveDts;

        // ê°ì²´ìƒì„± ë° ë°ì´í„° ë¡œë“œ (MapExpëŠ” UpdateAllì—ì„œ ê³„ì‚°ì‹ìœ¼ë¡œ ëŒ€ì…)
        missionArr = new MissionFormat[6] {
            new() { Type = svDts[0].Type, Lv = svDts[0].Lv, Exp = svDts[0].Exp, MaxExp = 0 },
            new() { Type = svDts[1].Type, Lv = svDts[1].Lv, Exp = svDts[1].Exp, MaxExp = 0 },
            new() { Type = svDts[2].Type, Lv = svDts[2].Lv, Exp = svDts[2].Exp, MaxExp = 0 },
            new() { Type = svDts[3].Type, Lv = svDts[3].Lv, Exp = svDts[3].Exp, MaxExp = 0 },
            new() { Type = svDts[4].Type, Lv = svDts[4].Lv, Exp = svDts[4].Exp, MaxExp = 0 },
            new() { Type = svDts[5].Type, Lv = svDts[5].Lv, Exp = svDts[5].Exp, MaxExp = 0 },
        };

        // UpdateAll();
        StartCoroutine(CoUpdateAllForSecond());
    }

    void Update()
    {
        //! TEST ë¯¸ì…˜ EXP ì¦ê°€
        if(GM._.stm.testMode.activeSelf && Input.GetKeyDown(KeyCode.C))
        {
            Debug.Log("TEST ë¯¸ì…˜ EXP ì¦ê°€");
            missionArr[(int)MISSION.MINING_ORE_CNT].Exp += 50;
            missionArr[(int)MISSION.MINING_TIME].Exp += 50;
            missionArr[(int)MISSION.UPGRADE_CNT].Exp += 10;
            missionArr[(int)MISSION.STAGE_CLEAR_CNT].Exp += 100;
            missionArr[(int)MISSION.MINING_CHEST_CNT].Exp += 10;
            missionArr[(int)MISSION.CHALLENGE_CLEAR_CNT].Exp += 10;
        }
    }

#region EVENT
    /// <summary>
    /// ë¯¸ì…˜ ë³´ìƒíšë“ ë²„íŠ¼
    /// </summary>
    /// <param name="idx"></param>
    public void OnClickAcceptRewardBtn(int idx) {
        var mission = missionArr[idx];

        if(mission.Exp < mission.MaxExp)
        {
            GM._.ui.ShowWarningMsgPopUp(LM._.Localize(LM.MissionStillMsg));
            return;
        }

        SoundManager._.PlaySfx(SoundManager.SFX.FameCompleteSFX);

        // ë¯¸ì…˜ ë ˆë²¨ ì—…
        mission.Lv++;

        // ë¯¸ì…˜ ë³´ìƒ
        GM._.rwm.ShowReward(missionArr[idx].Reward);

        // ì—…ë°ì´íŠ¸
        UpdateAll();

        // ì—…ë°ì´íŠ¸ ì•Œë¦¼UI ğŸ”´
        UpdateAlertRedDot();
    }

    /// <summary>
    /// í˜„ì¬ë ˆë²¨ ëª…ì˜ˆíŒì—… í‘œì‹œìš© (i)ì •ë³´ë²„íŠ¼
    /// </summary>
    public void OnClickFameInfoIconBtn()
    {
        SoundManager._.PlaySfx(SoundManager.SFX.ItemDrop1SFX);
        SetFameLevelToogleUI(isOn: false);
        ShowFameLevelUpGradeTable(isLvUp: false);
    }

    /// <summary>
    /// ëª…ì˜ˆì •ë³´í‘œì‹œ í† ê¸€ë²„íŠ¼
    /// </summary>
    public void OnClickNextLvInfoToogleHandle()
    {
        SoundManager._.PlaySfx(SoundManager.SFX.Tap2SFX);

        // í† ê¸€ UI
        SetFameLevelToogleUI(nextLvInfoToogleHandle.isOn);

        // í† ê¸€ë²„íŠ¼ì— ë”°ë¥¸ íŒì—… í‘œì‹œ
        if(nextLvInfoToogleHandle.isOn)
        {
            ShowFameNextLevelUpGradeTable();
        }
        else
        {
            ShowFameLevelUpGradeTable(false);
        }
    }
#endregion

#region FUNC
    /// <summary>
    /// ê²Œì„ì§„í–‰ì‹œ, 1ì´ˆë§ˆë‹¤ ì±„êµ´ë¯¸ì…˜ ì¦ê°€ ë° ì „ì²´ ë°ì´í„° ì—…ë°ì´íŠ¸
    /// </summary>
    /// <returns></returns>
    IEnumerator CoUpdateAllForSecond()
    {
        while(true)
        {
            if(GM._.gameState == GameState.PLAY)
            {
                Debug.Log("CoUpdateAllForSecond():: gameState=PLAY, ì—…ë°ì´íŠ¸ ëª…ì˜ˆ ë°ì´í„° ë° UI");
                // ì±„êµ´ì‹œê°„ ë¯¸ì…˜
                GM._.fm.missionArr[(int)MISSION.MINING_TIME].Exp++;

                UpdateAll();
            }
            yield return Util.TIME1;
        }
    }

    /// <summary>
    /// í˜„ì¬ ëª…ì˜ˆ ë° ë¯¸ì…˜ ë°ì´í„°ì™€ UI ì—…ë°ì´íŠ¸
    /// </summary>
    public void UpdateAll()
    {
        // ëª…ì˜ˆ ë°ì´í„° ì—…ë°ì´íŠ¸
        UpdateFameMapExp();

        // ëª…ì˜ˆ UI ì—…ë°ì´íŠ¸
        UpdateFameUI();

        // ë¯¸ì…˜ ë°ì´í„° ì—…ë°ì´íŠ¸
        for(int i = 0; i < missionArr.Length; i++)
            missionArr[i].UpdateData();

        // ë¯¸ì…˜ UI ì—…ë°ì´íŠ¸
        for(int i = 0; i < missionUIArr.Length; i++)
        {
            missionUIArr[i].UpdateUI(missionArr[i]);
        }
    }

    /// <summary>
    /// ëª…ì˜ˆë ˆë²¨ í•„ìš”ê²½í—˜ì¹˜ ( MAX 20LV )
    /// </summary>
    public void UpdateFameMapExp()
    {
        // ëª…ì˜ˆ ë ˆë²¨ì—…ì¸ ê²½ìš°
        if(FameExp >= fameMaxExp && FameLv < FAME_MAXLV)
        {
            // ì—…ë°ì´íŠ¸
            FameExp = FameExp - fameMaxExp; // ë ˆë²¨ì—…í›„ ë‚¨ì€ëŸ‰ ì ìš©
            FameLv++;
            GM._.spm.UpdateUI();

            GM._.ui.ShowNoticeMsgPopUp($"{LM._.Localize(LM.Fame)} {LM._.Localize(LM.Lv)} UP!");
            FameLevelUp();
        }
    }

    /// <summary>
    /// ëª…ì˜ˆë ˆë²¨ í•„ìš”ê²½í—˜ì¹˜ ê³„ì‚°ì‹
    /// </summary>
    private int CalcFameMaxExp(int fameLv)
    {
        return 10 + fameLv * (fameLv - 1) * 10 / 2;
    }

    /// <summary>
    /// ëª…ì˜ˆê²½í—˜ì¹˜ ìŠ¬ë¼ì´ë” ê°’
    /// </summary>
    public float GetFameExpSliderVal() {
        // MAX ë ˆë²¨ì´ë¼ë©´
        if(FameLv >= FAME_MAXLV)
            return 1; // FULL

        return (float)FameExp / fameMaxExp;
    } 

    /// <summary>
    /// ëª…ì˜ˆê²½í—˜ì¹˜ ìŠ¬ë¼ì´ë” ë¬¸ì
    /// </summary>
    /// <returns></returns>
    public string GetFameExpSliderStr() {
        // MAX ë ˆë²¨ì´ë¼ë©´
        if(FameLv >= FAME_MAXLV)
            return "MAX";

        return $"{FameExp} / {fameMaxExp}";
    } 

    /// <summary>
    /// ëª…ì˜ˆë ˆë²¨ í•„ìš”ê²½í—˜ì¹˜ UI ( MAX 20LV )
    /// </summary>
    private void UpdateFameUI()
    {
        fameLvTxt.text = FameLv.ToString();
        fameExpSlider.value = GetFameExpSliderVal();
        fameExpTxt.text = GetFameExpSliderStr();
    }

    /// <summary>
    /// ëª…ì˜ˆë ˆë²¨ì—… ë³´ìƒì§€ê¸‰
    /// </summary>
    private void FameLevelUp()
    {
        SoundManager._.PlaySfx(SoundManager.SFX.FameLvUpSFX);

        ShowFameLevelUpGradeTable(isLvUp: true);

        GM._.rwm.ShowReward (
            new Dictionary<RWD, int> {
                { RWD.ORE_CHEST,      (FameLv - 1) * 5 },
                { RWD.TREASURE_CHEST, (FameLv - 1) * 2 },
                { RWD.ORE_TICKET,     (FameLv - 1) * 5 },
                { RWD.RED_TICKET,     (FameLv - 1) * 2 },
                { RWD.CRISTAL,        (FameLv - 1) * 10 },
            }
        );
    }

    /// <summary>
    /// ëª…ì˜ˆ ë ˆë²¨ì—… íŒì—… í‘œì‹œ (ë ˆë²¨ì—…ì´ ì•„ë‹ê²½ìš°, í˜„ì¬ ì†Œí™˜ë“±ê¸‰ í‘œì‹œìš©)
    /// </summary>
    /// <param name="isLvUp">ë ˆë²¨ì—…ì¸ì§€ ì•„ë‹Œì§€</param>
    private void ShowFameLevelUpGradeTable(bool isLvUp) {
        // íŒì—… í‘œì‹œ
        fameLevelUpInfoPanel.SetActive(true);
        // íƒ€ì´í‹€
        fameLevelUpInfoPanelTitleTxt.text = isLvUp? $"{LM._.Localize(LM.Fame)} {LM._.Localize(LM.Lv)} UP!" : $"{LM._.Localize(LM.Fame)} {LM._.Localize(LM.Lv)}";
        // ë ˆë²¨ í…ìŠ¤íŠ¸
        fameLevelUpInfoPanelLvTxt.text = FameLv.ToString();

        // ëª¨ë“  ìë™ì±„êµ´ë³´ê´€ëŸ‰ ê³±í•˜ê¸°ê°’
        allAutoMiningStorageMultiplyValTxt.text = $"x {CalcAllAutoMiningStorageMultiVal(FameLv)}";

        // ë“±ê¸‰í‘œ ë°ì´í„°
        int[] curLvGrdValTb = GM._.fm.GetRandomGradeArrByFame(); // ë ˆë²¨ì—…í•œ í˜„ì¬ ë ˆë²¨í™•ë¥ 
        int[] befLvGrdValTb = GM._.fm.GetRandomGradeArrByFame(extraLv: -1); // ì´ì „ ë ˆë²¨í™•ë¥ 

        // ê° ë“±ê¸‰ ë¬¸ìì—´
        string commonGrade = $"{curLvGrdValTb[0]}%";
        string unCommonGrade = $"\n<color=green>{curLvGrdValTb[1]}%</color>";
        string rareGrade = $"\n<color=blue>{curLvGrdValTb[2]}%</color>";
        string uniqueGrade = $"\n<color=purple>{curLvGrdValTb[3]}%</color>";
        string legendGrade = $"\n<color=yellow>{curLvGrdValTb[4]}%</color>";
        string mythGrade = $"\n<color=red>{curLvGrdValTb[5]}%</color>";

        // ë ˆë²¨ì—… ê²½ìš°, "<= ì´ì „ ë ˆë²¨%" ìš°ì¸¡ì— í‘œì‹œ
        if(isLvUp)
        {
            commonGrade += $"<color=grey> <= {befLvGrdValTb[0]}%</color>";
            unCommonGrade += $"<color=grey> <= {befLvGrdValTb[1]}%</color>";
            rareGrade += $"<color=grey> <= {befLvGrdValTb[2]}%</color>";
            uniqueGrade += $"<color=grey> <= {befLvGrdValTb[3]}%</color>";
            legendGrade += $"<color=grey> <= {befLvGrdValTb[4]}%</color>";
            mythGrade += $"<color=grey> <= {befLvGrdValTb[5]}%</color>";
        }

        // ë“±ê¸‰í‘œ ì‘ì„±
        employRandomTableValTxt.text = commonGrade + unCommonGrade + rareGrade + uniqueGrade + legendGrade + mythGrade;
    }

    /// <summary>
    /// ëª¨ë“  ìë™ì±„êµ´ë³´ê´€ëŸ‰ ê³±í•˜ê¸°ê°’ ê³„ì‚°
    /// </summary>
    public int CalcAllAutoMiningStorageMultiVal(int fameLv)
    {
        return (int)Mathf.Pow(2, fameLv / 2);
    }

    /// <summary>
    /// ëª…ì˜ˆë ˆë²¨ì—… í† ê¸€UI ì—…ë°ì´íŠ¸
    /// </summary>
    /// <param name="isOn"></param>
    public void SetFameLevelToogleUI(bool isOn)
    {
        nextLvInfoToogleHandle.isOn = isOn;
        var toggleTxt = nextLvInfoToogleHandle.GetComponentInChildren<TMP_Text>();

        toggleTxt.text = isOn? "ON" : "OFF";
        nextLvInfoToogleHandle.GetComponent<Image>().color = isOn? Color.green : Color.white;
    }

    /// <summary>
    /// ë‹¤ìŒë ˆë²¨ ëª…ì˜ˆíŒì—… í‘œì‹œ
    /// </summary>
    public void ShowFameNextLevelUpGradeTable() {
        // íŒì—… í‘œì‹œ
        fameLevelUpInfoPanel.SetActive(true);
        // íƒ€ì´í‹€
        fameLevelUpInfoPanelTitleTxt.text = LM._.Localize(LM.NextFameLvGradeTable);
        // ë ˆë²¨ í…ìŠ¤íŠ¸
        fameLevelUpInfoPanelLvTxt.text = (FameLv + 1).ToString();

        // ëª¨ë“  ìë™ì±„êµ´ë³´ê´€ëŸ‰ ê³±í•˜ê¸°ê°’
        allAutoMiningStorageMultiplyValTxt.text = $"x {CalcAllAutoMiningStorageMultiVal(FameLv + 1)}";

        // ë“±ê¸‰í‘œ ë°ì´í„°
        int[] curLvGrdValTb = GM._.fm.GetRandomGradeArrByFame(); // í˜„ì¬ ë ˆë²¨í™•ë¥ 
        int[] nextLvGrdValTb = GM._.fm.GetRandomGradeArrByFame(extraLv: +1); // ë‹¤ìŒ ë ˆë²¨í™•ë¥ 

        // ê° ë“±ê¸‰ ë¬¸ìì—´
        string commonGrade = $"<color=grey>{curLvGrdValTb[0]}%";
        string unCommonGrade = $"\n<color=grey>{curLvGrdValTb[1]}%";
        string rareGrade = $"\n<color=grey>{curLvGrdValTb[2]}%";
        string uniqueGrade = $"\n<color=grey>{curLvGrdValTb[3]}%";
        string legendGrade = $"\n<color=grey>{curLvGrdValTb[4]}%";
        string mythGrade = $"\n<color=grey>{curLvGrdValTb[5]}%";

        // ë‹¤ìŒë ˆë²¨ ë“±ê¸‰í™•ë¥  ë¬¸ìì—´
        commonGrade += $" => </color>{nextLvGrdValTb[0]}%</color=grey>";
        unCommonGrade += $" => </color><color=green>{nextLvGrdValTb[1]}%</color>";
        rareGrade += $" => </color><color=blue>{nextLvGrdValTb[2]}%</color>";
        uniqueGrade += $" => </color><color=purple>{nextLvGrdValTb[3]}%</color>";
        legendGrade += $" => </color><color=yellow>{nextLvGrdValTb[4]}%</color>";
        mythGrade += $" => </color><color=red>{nextLvGrdValTb[5]}%</color>";

        // ë“±ê¸‰í‘œ ì‘ì„±
        employRandomTableValTxt.text = commonGrade + unCommonGrade + rareGrade + uniqueGrade + legendGrade + mythGrade;
    }

    /// <summary>
    /// ëª…ì˜ˆì— ë”°ë¥¸ ìºë¦­í„° ëœë¤ë“±ê¸‰ ë°°ì—´ ë°˜í™˜ (MAX 20LV)
    /// </summary>
    /// <returns>[ì¼ë°˜ , ê³ ê¸‰ , í¬ê·€ , ìœ ë‹ˆí¬ , ì „ì„¤ , ì‹ í™”]</returns>
    public int[] GetRandomGradeArrByFame(int extraLv = 0) {
        int lv = FameLv + extraLv;
        switch(lv) {
            case 1: return new int[] {70, 25, 3, 2, 0, 0};
            case 2: return new int[] {65, 30, 3, 2, 0, 0};
            case 3: return new int[] {60, 30, 6, 3, 1, 0};
            case 4: return new int[] {55, 35, 6, 3, 1, 0};
            case 5: return new int[] {50, 35, 9, 5, 1, 0};
            case 6: return new int[] {45, 40, 8, 5, 2, 0};
            case 7: return new int[] {40, 40, 12, 6, 2, 0};
            case 8: return new int[] {35, 45, 12, 6, 2, 0};
            case 9: return new int[] {30, 50, 12, 6, 2, 0};
            case 10: return new int[] {30, 50, 10, 7, 3, 0};
            case 11: return new int[] {25, 45, 15, 10, 4, 1};
            case 12: return new int[] {20, 45, 20, 10, 4, 1};
            case 13: return new int[] {15, 40, 25, 13, 6, 1};
            case 14: return new int[] {10, 40, 30, 13, 6, 1};
            case 15: return new int[] {5, 40, 35, 15, 9, 1};
            case 16: return new int[] {0, 35, 35, 20, 9, 1};
            case 17: return new int[] {0, 30, 40, 20, 9, 1};
            case 18: return new int[] {0, 20, 40, 25, 12, 3};
            case 19: return new int[] {0, 10, 30, 45, 12, 3};
            case 20: return new int[] {0, 0, 20, 60, 15, 5};
            case 21: return new int[] {0, 0, 20, 58, 17, 5};
            case 22: return new int[] {0, 0, 18, 57, 20, 5};
            case 23: return new int[] {0, 0, 18, 55, 21, 6};
            case 24: return new int[] {0, 0, 16, 55, 23, 6};
            case 25: return new int[] {0, 0, 14, 53, 26, 7};
            case 26: return new int[] {0, 0, 14, 50, 29, 7};
            case 27: return new int[] {0, 0, 12, 48, 32, 8};
            case 28: return new int[] {0, 0, 10, 45, 36, 9};
            case 29: return new int[] {0, 0, 5, 40, 45, 10};
            case 30: return new int[] {0, 0, 0, 35, 50, 15};
        }

        return null; // í•´ë‹¹ ë ˆë²¨ì´ ì•„ë‹Œê²½ìš° ì—ëŸ¬: nullë°˜í™˜
    }

    /// <summary>
    /// ìˆ˜ë ¹ê°€ëŠ¥í•œ ë²„íŠ¼ì´ ìˆë‹¤ë©´, ì•Œë¦¼ì•„ì´ì½˜UI ğŸ”´í‘œì‹œ
    /// </summary>
    public void UpdateAlertRedDot()
    {
        Debug.Log($"ëª…ì˜ˆ ë¯¸ì…˜:: UpdateAlertRedDot()::");
        bool isAcceptable = Array.Exists(missionArr, msi => msi.Exp >= msi.MaxExp);
        alertRedDotObj.SetActive(isAcceptable);
    }
#endregion
}
